version: '3.8'

services:
  gateway-service:
    image: ghcr.io/${GITHUB_REPOSITORY}/gateway-service:latest
    ports:
      - "${GATEWAY_PORT:-80}:8080"
    restart: always

  simple-service:
    image: ghcr.io/${GITHUB_REPOSITORY}/simple-service:latest
    expose:
      - "8080"
    restart: always

  inventory-service:
    image: ghcr.io/${GITHUB_REPOSITORY}/inventory-service:latest
    expose:
      - "8080"
    restart: always
