version: '3.8'

services:
  simple-service:
    image: ghcr.io/${GITHUB_REPOSITORY}/simple-service:latest
    ports:
      - "8080:8080"
    restart: always

  inventory-service:
    image: ghcr.io/${GITHUB_REPOSITORY}/inventory-service:latest
    ports:
      - "8081:8080"
    restart: always
