name: Inventory Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'inventory-service/**'
      - '.github/workflows/ci-inventory-service.yml'
      - '.github/workflows/reusable-build-deploy.yml'
      - 'compose.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'inventory-service/**'

permissions:
  packages: write

jobs:
  run-pipeline:
    uses: ./.github/workflows/reusable-build-deploy.yml
    with:
      service-name: inventory-service
